### ISSUE TITLE
Error in installation of ml_decoder module

### ISSUE THREAD

**Issue by christincha** [fwillett/speechBCI#10]
Dear authors, 

I am tyring to set up the environment of the project, but came across an error when installing the lm_decoder.
The error messages shown below:
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4hwpwonv/lm-decoder_6684c87b32754d8285ac3c5c1b5e752c/setup.py", line 54, in <module>
          ext_modules = [build.extension],
      AttributeError: module 'build' has no attribute 'extension'
      [end of output]
It seems to be caused by the build module, but I tried different versions of the build. This error message seems to be consistent.
Is it necessary to install the package? 
By the way, I didn't run the builLanguageModel.ipynb,  considering you have provided pre-trained trained language model. Could this be the reason for the error?

Thanks!

**Comment by cffan** [comment]
Yes, the `lm_decoder` module is necessary to run the decoder.

Seems like you might have a different version of python setuptools. Can you do `pip list` and paste the output here?

**Comment by christincha** [comment]
Sure, the following are the outputs of `pip list`, thanks!
Package                      Version      Editable project location
---------------------------- ------------ ----------------------------------------------------
absl-py                      2.0.0
accelerate                   0.20.3
alembic                      1.12.1
annotated-types              0.6.0
antlr4-python3-runtime       4.9.3
anyio                        4.0.0
appdirs                      1.4.4
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.4.1
astunparse                   1.6.3
async-lru                    2.0.4
async-timeout                4.0.3
attrs                        23.1.0
autopage                     0.5.2
Babel                        2.13.1
beautifulsoup4               4.12.2
bitsandbytes                 0.39.1
bleach                       6.1.0
blinker                      1.7.0
Brotli                       1.0.9
build                        0.0.1
cachetools                   5.3.2
certifi                      2023.7.22
cffi                         1.15.1
charset-normalizer           2.0.4
click                        8.1.7
cliff                        4.3.0
cloudpickle                  3.0.0
cmaes                        0.10.0
cmd2                         2.4.3
colorlog                     6.7.0
comm                         0.1.4
contourpy                    1.1.1
cryptography                 41.0.3
cycler                       0.12.1
debugpy                      1.8.0
decorator                    5.1.1
defusedxml                   0.7.1
Distance                     0.1.3
docker-pycreds               0.4.0
edit-distance                1.0.6
exceptiongroup               1.1.3
executing                    2.0.1
fastjsonschema               2.18.1
filelock                     3.13.1
Flask                        3.0.0
Flask-Compress               1.14
flatbuffers                  2.0.7
fonttools                    4.43.1
fqdn                         1.5.1
fsspec                       2023.10.0
g2p-en                       2.1.0
gast                         0.4.0
gitdb                        4.0.11
GitPython                    3.1.40
google-auth                  2.23.4
google-auth-oauthlib         1.1.0
google-pasta                 0.2.0
greenlet                     3.0.1
grpcio                       1.59.2
h5py                         3.10.0
hiplot                       0.1.33
huggingface-hub              0.18.0
hydra-core                   1.3.2
hydra-optuna-sweeper         1.2.0
hydra-submitit-launcher      1.1.5
idna                         3.4
importlib-metadata           6.8.0
importlib-resources          6.1.0
inflect                      7.0.0
ipykernel                    6.26.0
ipython                      8.17.2
ipywidgets                   8.1.1
isoduration                  20.11.0
itsdangerous                 2.1.2
jedi                         0.19.1
Jinja2                       3.1.2
joblib                       1.3.2
json5                        0.9.14
jsonpointer                  2.4
jsonschema                   4.19.2
jsonschema-specifications    2023.7.1
jupyter_client               8.5.0
jupyter_core                 5.5.0
jupyter-events               0.8.0
jupyter-lsp                  2.2.0
jupyter_server               2.9.1
jupyter_server_terminals     0.4.4
jupyterlab                   4.0.7
jupyterlab-pygments          0.2.2
jupyterlab_server            2.25.0
jupyterlab-widgets           3.0.9
keras                        2.7.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.5
libclang                     16.0.6
llvmlite                     0.41.1
Mako                         1.2.4
Markdown                     3.5.1
MarkupSafe                   2.1.3
matplotlib                   3.8.1
matplotlib-inline            0.1.6
mistune                      3.0.2
mkl-fft                      1.3.8
mkl-random                   1.2.4
mkl-service                  2.4.0
nbclient                     0.8.0
nbconvert                    7.10.0
nbformat                     5.9.2
nest-asyncio                 1.5.8
neural-decoder               0.0.1        /
nltk                         3.8.1
notebook                     7.0.6
notebook_shim                0.2.3
numba                        0.58.1
numpy                        1.25.0
nvidia-cublas-cu11           11.10.3.66
nvidia-cuda-nvrtc-cu11       11.7.99
nvidia-cuda-runtime-cu11     11.7.99
nvidia-cudnn-cu11            8.5.0.96
oauthlib                     3.2.2
omegaconf                    2.3.0
opt-einsum                   3.3.0
optuna                       2.10.1
overrides                    7.4.0
packaging                    23.2
pandas                       2.1.2
pandocfilters                1.5.0
parso                        0.8.3
pathtools                    0.1.2
pbr                          5.11.1
pep517                       0.13.0
pexpect                      4.8.0
Pillow                       10.0.1
pip                          23.3
platformdirs                 3.11.0
prettytable                  3.9.0
prometheus-client            0.18.0
prompt-toolkit               3.0.39
protobuf                     3.20.1
psutil                       5.9.6
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
pydantic                     2.4.2
pydantic_core                2.10.1
Pygments                     2.16.1
pyOpenSSL                    23.2.0
pyparsing                    3.1.1
pyperclip                    1.8.2
pyproject_hooks              1.0.0
PySocks                      1.7.1
python-dateutil              2.8.2
python-json-logger           2.0.7
pytz                         2023.3.post1
PyYAML                       6.0.1
pyzmq                        25.1.1
redis                        5.0.1
referencing                  0.30.2
regex                        2023.10.3
requests                     2.31.0
requests-oauthlib            1.3.1
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rpds-py                      0.10.6
rsa                          4.9
scikit-learn                 1.3.2
scipy                        1.11.1
seaborn                      0.12.2
Send2Trash                   1.8.2
sentry-sdk                   1.33.1
setproctitle                 1.3.3
setuptools                   68.0.0
six                          1.16.0
smmap                        5.0.1
sniffio                      1.3.0
soupsieve                    2.5
SQLAlchemy                   2.0.22
stack-data                   0.6.3
stevedore                    5.1.0
submitit                     1.5.0
tensorboard                  2.15.0
tensorboard-data-server      0.7.2
tensorflow-estimator         2.7.0
tensorflow-gpu               2.7.0
tensorflow-io-gcs-filesystem 0.34.0
termcolor                    2.3.0
terminado                    0.17.1
threadpoolctl                3.2.0
tinycss2                     1.2.1
tokenizers                   0.13.3
toml                         0.10.2
tomli                        2.0.1
torch                        1.13.1
torchaudio                   0.13.1
torchvision                  0.14.1
tornado                      6.3.3
tqdm                         4.66.1
traitlets                    5.13.0
transformers                 4.28.1
types-python-dateutil        2.8.19.14
typing_extensions            4.7.1
tzdata                       2023.3
uri-template                 1.3.0
urllib3                      1.26.18
wandb                        0.15.5
wcwidth                      0.2.9
webcolors                    1.13
webencodings                 0.5.1
websocket-client             1.6.4
Werkzeug                     3.0.1
wheel                        0.41.2
widgetsnbextension           4.0.9
wrapt                        1.15.0
zipp                         3.17.0

**Comment by cffan** [comment]
The setuptools seems alright. What's your operating system? What versions of gcc and cmake do you have? Do you use virtualenv or conda to set up python environment?

**Comment by christincha** [comment]
I am using Linux OS with a virtual environment with gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 and cmake version 3.27.7

Thanks!

**Comment by christincha** [comment]
I tried on another system with Ubuntu 20.04 GCC 10.5.0, cmake 3.16.3, but it still shows: AttributeError: module 'build' has no attribute 'extension'.

**Comment by christincha** [comment]
I think the problem may related to the build. At the very beginning, we met the error:  there is no` build ` package, which build are you using when install the lm_decoder?

**Comment by cffan** [comment]
What is this `build 0.0.1` package in your python virtual environment? Can you uninstall it and try installing the `lm_decoder` again?

**Comment by christincha** [comment]
Dear Author,
Thanks for the feedback. It works now.
