### ISSUE TITLE
release of weights used from models trained for project.

### ISSUE THREAD

**Issue by bparbhu** [fwillett/speechBCI#8]
Hey all,

For the competition, is it possible to release the model weights that were derived from the project. 
I noticed you use weights and biases as a service and it's an amazing framework for mlops but we would like to be able to 
know if we experience differences in replicating your work and also planning improvements in our own models.
Any help with this is much appreciated and is very welcome.

Thanks again,

-Brian

**Comment by fwillett** [comment]
Hi Brian,

Yes, we released the model weights on [Dryad](https://datadryad.org/stash/dataset/doi:10.5061/dryad.x69p8czpq) along with the dataset, they're in the derived.tar.gz file. They're the output of the [training notebook](https://github.com/fwillett/speechBCI/blob/main/AnalysisExamples/rnn_step2_trainBaselineRNN.ipynb) when we ran the code ourselves. 

Best,
Frank

**Comment by bparbhu** [comment]
Awesome, thanks again Frank and much appreciated!
